message(STATUS "----------------- fixup app ${APP} ${LIBDIRS}")
string(REPLACE " " ";" SEMICOLONS ${LIBDIRS})
foreach (TOKEN ${SEMICOLONS})
	string(REPLACE "_IwasaSPACE_" " " ACTUALTOKEN ${TOKEN})
	list(APPEND IMPORTANTDIRS "${ACTUALTOKEN}")
endforeach()

message(STATUS "--------------- Hello Lee.  Here is your list")
foreach (LIB ${IMPORTANTDIRS})
	message(STATUS ">${LIB}<")
endforeach()
message(STATUS "---------------- Thats all folks")
include(BundleUtilities)
fixup_bundle("${APP}" "" "${IMPORTANTDIRS}")